{{- if .Values.secrets }}
{{- range $key, $value := .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .name | replace "_" "-" | lower }}-secret"
  namespace: {{ include "kube-go-exec.serviceAccountNamespace" $ }}
  labels:
    {{- include "kube-go-exec.labels" $ | nindent 4 }}
type: Opaque
data:
  {{ .name }}: {{ .value | b64enc | quote }}
---
{{- end }}
{{- end }}
